<section class="login">
<h2>Login</h2>
<?php if ($this->error): ?>
	<p class="error">
		Wrong login credentials
	</p>
<?php endif ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL,
array('controller'=>'Login', 'action' => 'process')));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>

<dl class="zend_form">
<dt><?php echo $this->formLabel($form->get('email')); ?></dt>
<dd><?php
echo $this->formElement($form->get('email'));
?></dd>
<dt><?php echo $this->formLabel($form->get('password'));
?></dt>
<dd><?php
echo $this->formElement($form->get('password'));
?></dd>
<dd><?php
echo $this->formElement($form->get('submit'));
?></dd>
<?php echo $this->form()->closeTag() ?>
</section>